# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xpd6c6zw6xEA8pAQjup_9eTGwIAmEi9g
"""

num_filas = 4
num_columnas = 10

dep_disponibles = [[' ' for _ in range(num_columnas)] for _ in range(num_filas)]

def mostrar_disponibilidad_dep():
    print("Departamentos Disponibles:")
    for fila in dep_disponibles:
        for dep in fila:
            print('[X]' if dep == 'X' else '[ ]', end=' ')
        print()

def seleccionar_dep():
    while True:
        fila = int(input("Ingrese la fila del Departamento: "))
        columna = int(input("Ingrese la columna del Departamento: "))

        if 0 <= fila < num_filas and 0 <= columna < num_columnas:
            if dep_disponibles[fila][columna] == ' ':
                dep_disponibles[fila][columna] = 'X'
                return fila, columna
            else:
                print("la seleccion de este Departamento ya no esta disponible.seleccione otro")
        else:
            print("vuelva a seleccionar.")

print("Bienvenido seleciona el Departamento que deseas.")
mostrar_disponibilidad_dep()

fila, columna = seleccionar_dep()
print(f"Departamento seleccionado: Fila {fila}, Columna {columna}.")